spring:
  datasource:
    url: jdbc:h2:mem:mydb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  hibernate:
    ddl-auto: update

  jpa:
    hibernate:
      ddl-auto: update # ou create-drop, update, etc.
    show-sql: true # Mostra as consultas SQL no console